apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.exposePort }}
    port: {{ .Values.service.internalPort }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "webapp.selectorLabels" . | nindent 4 }}
